### ISSUE TITLE
After the dataset is downloaded, it cannot be decompressed normally

### ISSUE THREAD

**Issue by waiterxiaoyy** [LMMMEng/LLD-MMRI2023#1]
After I download the dataset, I want to decompress the dataset, but they all prompt that the file is empty. Is it my problem or is this a common problem?

**Comment by LMMMEng** [comment]
Hi, you need to concatenate multiple subfiles first before decompressing, please refer to https://github.com/LMMMEng/LLD-MMRI2023/tree/main/main#1-download-and-extract-dataset

**Comment by waiterxiaoyy** [comment]
Oh!! It was my problem, I noticed it, thank you very much for your help!

**Comment by LMMMEng** [comment]
Thanks for your interest and good luck!
