### ISSUE TITLE
Inquiry about the Release of Validation Set Annotations

### ISSUE THREAD

**Issue by waiterxiaoyy** [LMMMEng/LLD-MMRI2023#10]
Dear Competition Organizer's,

I am writing to inquire about the release of the annotations for the validation set. As per the schedule provided, it was mentioned that the annotations would be released on July 8th. However, to date, I have not been able to access the annotations.

I would be grateful if you could kindly provide an update regarding the release of the annotations for the validation set.Having access to the validation set annotations is crucial for participants like me to evaluate and refine our models effectively.

Thank you very much for your attention to this matter. I look forward to your response and appreciate your assistance in resolving this issue.

**Comment by LMMMEng** [comment]
Hi, sorry for the delay. We will release the label of the validation set within 24 hours, once the label is released, you will receive an email, please stay tuned.
