### ISSUE TITLE
No access to validation set labels

### ISSUE THREAD

**Issue by hannesk95** [LMMMEng/LLD-MMRI2023#11]
Dear LLD-MMRI 2023 Team,

could you please provide more information about how to access the labels of the validation set?

Thanks in advance!

**Comment by wllfore** [comment]
Please inform us the time of releasing the labels of the validation set as soon as possible.

**Comment by LangDaniel** [comment]
`July 8th: Release the annotations of the validation set` is already checked off, but where can we find the data?
Please, can you provide us with a link?

**Comment by StefanFischer** [comment]
Sorry, did also not find any information on that.
