### ISSUE TITLE
Are the training and test sets for the competition allowed to be publicly disseminated?

### ISSUE THREAD

**Issue by Jiangj512** [LMMMEng/LLD-MMRI2023#12]
Are the training and test sets for the competition allowed to be publicly disseminated?

**Comment by Batman0096** [comment]
In your open access repo (https://github.com/Jiangj512/LLD_Project), the whole project link (baidu pan: https://pan.baidu.com/s/168hN8m6h3YLVPo2mdyVSvw?pwd=nlef) is expired, could you update with new link? Thank you very much!

**Comment by Jiangj512** [comment]
I'm not sure if the organizers are allowing the dataset to be made public. I'm still waiting to hear back from the organizers.

**Comment by LMMMEng** [comment]
The dataset will be made public recently, but we haven't set a date yet. I'll get back to you on this issue once it's released.

**Comment by LMMMEng** [comment]
The dataset has been released (https://github.com/LMMMEng/LLD-MMRI-Dataset).
