### ISSUE TITLE
What's training strategy? Is it 5-fold? How  to evaluate the validation/test dataset? 

### ISSUE THREAD

**Issue by Wangrui-berry** [LMMMEng/LLD-MMRI2023#13]
The raw data has been divided into 5-fold sub-datasets. However, the original code (main.py) could only process one-fold data every time. What is the actual process of training and validating? How can it be validated by randomly selecting 5-fold, only 1-fold, or the provided 5-fold?

**Comment by LMMMEng** [comment]
Sorry for the late response. In fact, all of the 5-fold sub-datasets we give are training sets, which are for performance evaluation in the early stage of the challenge. After that, we released validation sets and test sets for participants to evaluate their methods.
