### ISSUE TITLE
关于LLD-MMRI2023数据集MRI数据阶段区分的咨询

### ISSUE THREAD

**Issue by luomu58** [LMMMEng/LLD-MMRI2023#15]
我想问一下怎样区分各个阶段，尤其是增强后的动脉，门静脉和延迟阶段？非常感谢

**Comment by LMMMEng** [comment]
不同期相的标注在 .json 标注文件里可以找到

**Comment by luomu58** [comment]
好嘞&nbsp; 非常感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LMMMEng/LLD-MMRI2023"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月21日(星期天) 下午2:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LMMMEng/LLD-MMRI2023] 关于LLD-MMRI2023数据集MRI数据阶段区分的咨询 (Issue #15)





 
不同期相的标注在 .json 标注文件里可以找到
