### ISSUE TITLE
Spacing  information is listed in 'Annotation.json'

### ISSUE THREAD

**Issue by aa1234241** [LMMMEng/LLD-MMRI2023#2]
Hello,
I checked the full image using ITK-SNAP and I found that the shown spacing is 1x1x1mm which is inconsistent with the true data volume. Maybe the authors only change the nii files' head but not resample the nii volume?
<img width="721" alt="Screen Shot 2023-04-28 at 7 06 09 PM" src="https://user-images.githubusercontent.com/24704252/235131986-971e7e3a-da2c-4b66-8022-3d6e5fc2016e.png">

**Comment by LMMMEng** [comment]
Thank you for pointing out this issue. For detailed spacing of each volume, please refer to the annotated file 'data/labels/Annotation.json'

**Comment by aa1234241** [comment]
Many thanks! I have one related question. If only the spacing is given, is the affine matrix related to the volume (voxel space to Nifti space) limited to an orthogonal matrix? I have seen some MRI images with a non-orthogonal affine matrix in clinical images, so I just want to know if there are cases in the dataset that possibly have a non-orthogonal affine matrix.

**Comment by jehovahxu** [comment]
> Many thanks! I have one related question. If only the spacing is given, is the affine matrix related to the volume (voxel space to Nifti space) limited to an orthogonal matrix? I have seen some MRI images with a non-orthogonal affine matrix in clinical images, so I just want to know if there are cases in the dataset that possibly have a non-orthogonal affine matrix.

We have done some transforms in images,   but you can think of the affine matrix as being orthonormal

**Comment by aa1234241** [comment]
I see, thank you!
