### ISSUE TITLE
I can't decompress the concatenated dataset zip file

### ISSUE THREAD

**Issue by TshellT** [LMMMEng/LLD-MMRI2023#3]
Like this issue "https://github.com/LMMMEng/LLD-MMRI2023/issues/1", I used the command "type lld_mmri2023_part0* > lld_mmri2023.zip" to concatenate the dataset files to a new dataset file. But I also can't decompress the new dataset file. Additionally, I use the command "unzip lld_mmri2023.zip", it shows a error "Trying to read large file (> 2 GiB) without large file support".
The Windows system is used to conduct these operations.

**Comment by wangshuxinxinxin** [comment]
Hi, I have tried it on a Windows system, and everything is OK. Please check whether the data is completely downloaded and whether the concatenation command is correctly executed.
![image](https://github.com/LMMMEng/LLD-MMRI2023/assets/11481826/f46cac12-251e-4415-a4b1-7d2b6c299188)
![image](https://github.com/LMMMEng/LLD-MMRI2023/assets/11481826/5283d9bc-7c85-4fa0-95b5-b0825b3b0726)

**Comment by TshellT** [comment]
Get! Actually, I used the command "type lld_mmri2023_part0* > lld_mmri2023.zip" to concatenate the dataset files in Windows which from https://github.com/LMMMEng/LLD-MMRI2023/tree/main/main#1-download-and-extract-dataset, it is also failed concatenated. However, I use the command "cat lld_mmri2023_part0* > lld_mmri2023.zip" can successfully concatenate the dataset files in Ubuntu.
Maybe the command "type lld_mmri2023_part0* > lld_mmri2023.zip" can't conduct successfully in Windows.
