### ISSUE TITLE
The performance of baseline I run seems error

### ISSUE THREAD

**Issue by TshellT** [LMMMEng/LLD-MMRI2023#5]
I run the baseline, but the results seem a bit incorrect.
I achieve the best value in validation:
acc: 0.36923076923076925
f1: 0.24474850546279117
recall: 0.2687074829931973
precision: 0.2650609080841639
kappa: 0.16718749999999993
The performance is too low. Can you provide the classification performance of baseline you running?

**Comment by wangshuxinxinxin** [comment]
Hi, we have provided a checkpoint in the file https://github.com/LMMMEng/LLD-MMRI2023/blob/main/main/output/20230411-192839-uniformer_small_IL/summary.csv. We generate 5-fold cross-validated and this file presents one of the fold checkpoints during training.

**Comment by TshellT** [comment]
Get! Thanks!
