### ISSUE TITLE
The given z spacing ('slice_thickness') is incorrect on contrast-enhenced phase.

### ISSUE THREAD

**Issue by aa1234241** [LMMMEng/LLD-MMRI2023#6]
Hello,
I recovered the original image spacing by using the given annotations. I found the Z spacing of the contrast-enhenced phases are incorrect, as shown in the below image. Other phases' spacing are visually correct.
<img width="1575" alt="Screen Shot 2023-05-31 at 10 12 01 PM" src="https://github.com/LMMMEng/LLD-MMRI2023/assets/24704252/91d9d1d9-1946-4d9e-8593-cb97729656f1">

**Comment by aa1234241** [comment]
The case name is MR104842 in the image.  Also other cases have the same issue.

**Comment by aa1234241** [comment]
solved.

**Comment by LMMMEng** [comment]
Hi, thank you for your interest. In fact, slice thickness is not necessarily equal to slice spacing in MRI images. In order to help you further, we will update the slice spacing in the annotation file recently, please pay attention to your mailbox.

**Comment by aa1234241** [comment]
That's great! Thank you!

**Comment by LMMMEng** [comment]
The annotation has been updated via E-mail, please check it.

**Comment by aa1234241** [comment]
I see. Thank you.
