### ISSUE TITLE
Data Link

### ISSUE THREAD

**Issue by JoshuaYang0926** [LMMMEng/LLD-MMRI2023#7]
Hi! My team "Liuhuhu" already filled in the registration information, but we have not received the data link, plz tell us if there is anything wrong.Thanks!

**Comment by LMMMEng** [comment]
Hi, sorry for the delay, the data link has been sent, please check the corresponding person's mailbox.

**Comment by JoshuaYang0926** [comment]
Thank you! I have received the data link from the official mailbox.
&nbsp;


MasterY
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年6月2日(星期五) 晚上8:14
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [LMMMEng/LLD-MMRI2023] Data Link (Issue #7)





 
Hi, sorry for the delay, the data link has been sent, please check the corresponding person's mailbox.
