### ISSUE TITLE
Has the data been resampled?

### ISSUE THREAD

**Issue by LinZ-web** [LMMMEng/LLD-MMRI2023#8]
Hi!
I used the code 'image.GetSpacing()' and found that the voxel of all data is (1.0, 1.0, 1.0). Has the data been resampled?

**Comment by LMMMEng** [comment]
Hi,

Data is not resampled. The detailed spacing information for each volume can be found in the annotation file.

**Comment by LinZ-web** [comment]
OK！Thanks！

**Comment by LinZ-web** [comment]
But Why the original spacing I obtained from the nii file is (1.0, 1.0, 1.0) instead of the information you gave us? (ps. I use the codes as follows)
![image](https://github.com/LMMMEng/LLD-MMRI2023/assets/53364019/f3dc8837-75f9-4849-96d9-b769413b34fe)
The situation of origin is the same.

**Comment by LMMMEng** [comment]
The actual spacing information is not recorded in the nii file, you should refer to the annotation file.

**Comment by LinZ-web** [comment]
Got it!
Thank you!
